name: Upload to GCS on Merge

on:
  push:
    branches: [ main ]
    paths:
      - 'index.html'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: git clone
      uses: actions/checkout@v3
      with:
        repository: robschn/ohgustie-com

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: 'index.html'
        destination: 'www.ohgustie.com'